server:
  port: ${SERVER_PORT}

springdoc:
  swagger-ui:
    path: /

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CLOUD_CONFIG_URL:http://localhost:8888/}