server:
  port: ${SERVER_PORT}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rnzmndz/project-site-monitoring-config.git
          default-label: ${SPRING_PROFILES_ACTIVE:default}
          clone-on-start: true
#          username: ${GIT_USERNAME:}
#          password: ${GIT_PASSWORD:}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}