spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rnzmndz/project-site-monitoring-config.git
          default-label: ${ACTIVE_PROFILE}
          clone-on-start: true